name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Install Selenium dependencies
        run: npm install selenium-webdriver chromedriver

      - name: Run Selenium tests
        run: npm run selenium-test

      # Add deployment steps if needed
