name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Install Selenium dependencies
        run: npm install selenium-webdriver chromedriver

      - name: Run Selenium tests
        run: npm run selenium-test

      # Add deployment steps if needed
